edition = "2023";

package diff;

import "diff/segment.proto";
import "diff/value.proto";

option go_package = "github.com/lesomnus/protobuf-diff/dpb";

message Delta {
  repeated Entry entries = 1;
}

message Entry {
  // If no path nor targets are specified, the op applies to the root.

  Path path = 1;

  repeated Segment targets = 2;

  //
  oneof kind {
    bool remove = 3;
    Value test = 4;
    Value insert = 5;
    Value assign = 6;
    FieldSegment move = 7;
    FieldSegment copy = 8;

    Delta nest = 15;
  }
}
