// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: diff/delta.proto

package dpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Delta struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entries *[]*Entry              `protobuf:"bytes,1,rep,name=entries"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_diff_delta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_diff_delta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Delta) GetEntries() []*Entry {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *Delta) SetEntries(v []*Entry) {
	x.xxx_hidden_Entries = &v
}

type Delta_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entries []*Entry
}

func (b0 Delta_builder) Build() *Delta {
	m0 := &Delta{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	return m0
}

type Entry struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path    *Path                  `protobuf:"bytes,1,opt,name=path"`
	xxx_hidden_Targets *[]*Segment            `protobuf:"bytes,2,rep,name=targets"`
	xxx_hidden_Kind    isEntry_Kind           `protobuf_oneof:"kind"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_diff_delta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_diff_delta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Entry) GetPath() *Path {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return nil
}

func (x *Entry) GetTargets() []*Segment {
	if x != nil {
		if x.xxx_hidden_Targets != nil {
			return *x.xxx_hidden_Targets
		}
	}
	return nil
}

func (x *Entry) GetRemove() bool {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Remove); ok {
			return x.Remove
		}
	}
	return false
}

func (x *Entry) GetTest() *Value {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Test); ok {
			return x.Test
		}
	}
	return nil
}

func (x *Entry) GetInsert() *Value {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Insert); ok {
			return x.Insert
		}
	}
	return nil
}

func (x *Entry) GetAssign() *Value {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Assign); ok {
			return x.Assign
		}
	}
	return nil
}

func (x *Entry) GetMove() *FieldSegment {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *Entry) GetCopy() *FieldSegment {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Copy); ok {
			return x.Copy
		}
	}
	return nil
}

func (x *Entry) GetNest() *Delta {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Nest); ok {
			return x.Nest
		}
	}
	return nil
}

func (x *Entry) SetPath(v *Path) {
	x.xxx_hidden_Path = v
}

func (x *Entry) SetTargets(v []*Segment) {
	x.xxx_hidden_Targets = &v
}

func (x *Entry) SetRemove(v bool) {
	x.xxx_hidden_Kind = &entry_Remove{v}
}

func (x *Entry) SetTest(v *Value) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &entry_Test{v}
}

func (x *Entry) SetInsert(v *Value) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &entry_Insert{v}
}

func (x *Entry) SetAssign(v *Value) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &entry_Assign{v}
}

func (x *Entry) SetMove(v *FieldSegment) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &entry_Move{v}
}

func (x *Entry) SetCopy(v *FieldSegment) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &entry_Copy{v}
}

func (x *Entry) SetNest(v *Delta) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &entry_Nest{v}
}

func (x *Entry) HasPath() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Path != nil
}

func (x *Entry) HasKind() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kind != nil
}

func (x *Entry) HasRemove() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Remove)
	return ok
}

func (x *Entry) HasTest() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Test)
	return ok
}

func (x *Entry) HasInsert() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Insert)
	return ok
}

func (x *Entry) HasAssign() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Assign)
	return ok
}

func (x *Entry) HasMove() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Move)
	return ok
}

func (x *Entry) HasCopy() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Copy)
	return ok
}

func (x *Entry) HasNest() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Nest)
	return ok
}

func (x *Entry) ClearPath() {
	x.xxx_hidden_Path = nil
}

func (x *Entry) ClearKind() {
	x.xxx_hidden_Kind = nil
}

func (x *Entry) ClearRemove() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Remove); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Entry) ClearTest() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Test); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Entry) ClearInsert() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Insert); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Entry) ClearAssign() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Assign); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Entry) ClearMove() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Move); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Entry) ClearCopy() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Copy); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Entry) ClearNest() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Nest); ok {
		x.xxx_hidden_Kind = nil
	}
}

const Entry_Kind_not_set_case case_Entry_Kind = 0
const Entry_Remove_case case_Entry_Kind = 3
const Entry_Test_case case_Entry_Kind = 4
const Entry_Insert_case case_Entry_Kind = 5
const Entry_Assign_case case_Entry_Kind = 6
const Entry_Move_case case_Entry_Kind = 7
const Entry_Copy_case case_Entry_Kind = 8
const Entry_Nest_case case_Entry_Kind = 15

func (x *Entry) WhichKind() case_Entry_Kind {
	if x == nil {
		return Entry_Kind_not_set_case
	}
	switch x.xxx_hidden_Kind.(type) {
	case *entry_Remove:
		return Entry_Remove_case
	case *entry_Test:
		return Entry_Test_case
	case *entry_Insert:
		return Entry_Insert_case
	case *entry_Assign:
		return Entry_Assign_case
	case *entry_Move:
		return Entry_Move_case
	case *entry_Copy:
		return Entry_Copy_case
	case *entry_Nest:
		return Entry_Nest_case
	default:
		return Entry_Kind_not_set_case
	}
}

type Entry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Path    *Path
	Targets []*Segment
	//

	// Fields of oneof xxx_hidden_Kind:
	Remove *bool
	Test   *Value
	Insert *Value
	Assign *Value
	Move   *FieldSegment
	Copy   *FieldSegment
	Nest   *Delta
	// -- end of xxx_hidden_Kind
}

func (b0 Entry_builder) Build() *Entry {
	m0 := &Entry{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Path = b.Path
	x.xxx_hidden_Targets = &b.Targets
	if b.Remove != nil {
		x.xxx_hidden_Kind = &entry_Remove{*b.Remove}
	}
	if b.Test != nil {
		x.xxx_hidden_Kind = &entry_Test{b.Test}
	}
	if b.Insert != nil {
		x.xxx_hidden_Kind = &entry_Insert{b.Insert}
	}
	if b.Assign != nil {
		x.xxx_hidden_Kind = &entry_Assign{b.Assign}
	}
	if b.Move != nil {
		x.xxx_hidden_Kind = &entry_Move{b.Move}
	}
	if b.Copy != nil {
		x.xxx_hidden_Kind = &entry_Copy{b.Copy}
	}
	if b.Nest != nil {
		x.xxx_hidden_Kind = &entry_Nest{b.Nest}
	}
	return m0
}

type case_Entry_Kind protoreflect.FieldNumber

func (x case_Entry_Kind) String() string {
	md := file_diff_delta_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isEntry_Kind interface {
	isEntry_Kind()
}

type entry_Remove struct {
	Remove bool `protobuf:"varint,3,opt,name=remove,oneof"`
}

type entry_Test struct {
	Test *Value `protobuf:"bytes,4,opt,name=test,oneof"`
}

type entry_Insert struct {
	Insert *Value `protobuf:"bytes,5,opt,name=insert,oneof"`
}

type entry_Assign struct {
	Assign *Value `protobuf:"bytes,6,opt,name=assign,oneof"`
}

type entry_Move struct {
	Move *FieldSegment `protobuf:"bytes,7,opt,name=move,oneof"`
}

type entry_Copy struct {
	Copy *FieldSegment `protobuf:"bytes,8,opt,name=copy,oneof"`
}

type entry_Nest struct {
	Nest *Delta `protobuf:"bytes,15,opt,name=nest,oneof"`
}

func (*entry_Remove) isEntry_Kind() {}

func (*entry_Test) isEntry_Kind() {}

func (*entry_Insert) isEntry_Kind() {}

func (*entry_Assign) isEntry_Kind() {}

func (*entry_Move) isEntry_Kind() {}

func (*entry_Copy) isEntry_Kind() {}

func (*entry_Nest) isEntry_Kind() {}

var File_diff_delta_proto protoreflect.FileDescriptor

const file_diff_delta_proto_rawDesc = "" +
	"\n" +
	"\x10diff/delta.proto\x12\x04diff\x1a\x12diff/segment.proto\x1a\x10diff/value.proto\".\n" +
	"\x05Delta\x12%\n" +
	"\aentries\x18\x01 \x03(\v2\v.diff.EntryR\aentries\"\xda\x02\n" +
	"\x05Entry\x12\x1e\n" +
	"\x04path\x18\x01 \x01(\v2\n" +
	".diff.PathR\x04path\x12'\n" +
	"\atargets\x18\x02 \x03(\v2\r.diff.SegmentR\atargets\x12\x18\n" +
	"\x06remove\x18\x03 \x01(\bH\x00R\x06remove\x12!\n" +
	"\x04test\x18\x04 \x01(\v2\v.diff.ValueH\x00R\x04test\x12%\n" +
	"\x06insert\x18\x05 \x01(\v2\v.diff.ValueH\x00R\x06insert\x12%\n" +
	"\x06assign\x18\x06 \x01(\v2\v.diff.ValueH\x00R\x06assign\x12(\n" +
	"\x04move\x18\a \x01(\v2\x12.diff.FieldSegmentH\x00R\x04move\x12(\n" +
	"\x04copy\x18\b \x01(\v2\x12.diff.FieldSegmentH\x00R\x04copy\x12!\n" +
	"\x04nest\x18\x0f \x01(\v2\v.diff.DeltaH\x00R\x04nestB\x06\n" +
	"\x04kindB'Z%github.com/lesomnus/protobuf-diff/dpbb\beditionsp\xe8\a"

var file_diff_delta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_diff_delta_proto_goTypes = []any{
	(*Delta)(nil),        // 0: diff.Delta
	(*Entry)(nil),        // 1: diff.Entry
	(*Path)(nil),         // 2: diff.Path
	(*Segment)(nil),      // 3: diff.Segment
	(*Value)(nil),        // 4: diff.Value
	(*FieldSegment)(nil), // 5: diff.FieldSegment
}
var file_diff_delta_proto_depIdxs = []int32{
	1, // 0: diff.Delta.entries:type_name -> diff.Entry
	2, // 1: diff.Entry.path:type_name -> diff.Path
	3, // 2: diff.Entry.targets:type_name -> diff.Segment
	4, // 3: diff.Entry.test:type_name -> diff.Value
	4, // 4: diff.Entry.insert:type_name -> diff.Value
	4, // 5: diff.Entry.assign:type_name -> diff.Value
	5, // 6: diff.Entry.move:type_name -> diff.FieldSegment
	5, // 7: diff.Entry.copy:type_name -> diff.FieldSegment
	0, // 8: diff.Entry.nest:type_name -> diff.Delta
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_diff_delta_proto_init() }
func file_diff_delta_proto_init() {
	if File_diff_delta_proto != nil {
		return
	}
	file_diff_segment_proto_init()
	file_diff_value_proto_init()
	file_diff_delta_proto_msgTypes[1].OneofWrappers = []any{
		(*entry_Remove)(nil),
		(*entry_Test)(nil),
		(*entry_Insert)(nil),
		(*entry_Assign)(nil),
		(*entry_Move)(nil),
		(*entry_Copy)(nil),
		(*entry_Nest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_diff_delta_proto_rawDesc), len(file_diff_delta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_diff_delta_proto_goTypes,
		DependencyIndexes: file_diff_delta_proto_depIdxs,
		MessageInfos:      file_diff_delta_proto_msgTypes,
	}.Build()
	File_diff_delta_proto = out.File
	file_diff_delta_proto_goTypes = nil
	file_diff_delta_proto_depIdxs = nil
}
