// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/diff/delta.proto

package dpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Delta struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entries *[]*Entry              `protobuf:"bytes,1,rep,name=entries"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_proto_diff_delta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diff_delta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Delta) GetEntries() []*Entry {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *Delta) SetEntries(v []*Entry) {
	x.xxx_hidden_Entries = &v
}

type Delta_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entries []*Entry
}

func (b0 Delta_builder) Build() *Delta {
	m0 := &Delta{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	return m0
}

type Entry struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Targets     []byte                 `protobuf:"bytes,1,opt,name=targets"`
	xxx_hidden_NoInsert    bool                   `protobuf:"varint,2,opt,name=no_insert,json=noInsert"`
	xxx_hidden_NoUpdate    bool                   `protobuf:"varint,3,opt,name=no_update,json=noUpdate"`
	xxx_hidden_Kind        isEntry_Kind           `protobuf_oneof:"kind"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_proto_diff_delta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diff_delta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Entry) GetTargets() []byte {
	if x != nil {
		return x.xxx_hidden_Targets
	}
	return nil
}

func (x *Entry) GetNoInsert() bool {
	if x != nil {
		return x.xxx_hidden_NoInsert
	}
	return false
}

func (x *Entry) GetNoUpdate() bool {
	if x != nil {
		return x.xxx_hidden_NoUpdate
	}
	return false
}

func (x *Entry) GetDeleted() bool {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Deleted); ok {
			return x.Deleted
		}
	}
	return false
}

func (x *Entry) GetAssigned() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Assigned); ok {
			return x.Assigned
		}
	}
	return nil
}

func (x *Entry) GetMerged() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Merged); ok {
			return x.Merged
		}
	}
	return nil
}

func (x *Entry) GetCopied() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Copied); ok {
			return x.Copied
		}
	}
	return nil
}

func (x *Entry) GetScattered() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Scattered); ok {
			return x.Scattered
		}
	}
	return nil
}

func (x *Entry) GetSwapped() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Swapped); ok {
			return x.Swapped
		}
	}
	return nil
}

func (x *Entry) GetEdited() *Edit {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Edited); ok {
			return x.Edited
		}
	}
	return nil
}

func (x *Entry) GetNested() *Delta {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*entry_Nested); ok {
			return x.Nested
		}
	}
	return nil
}

func (x *Entry) SetTargets(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Targets = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Entry) SetNoInsert(v bool) {
	x.xxx_hidden_NoInsert = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Entry) SetNoUpdate(v bool) {
	x.xxx_hidden_NoUpdate = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Entry) SetDeleted(v bool) {
	x.xxx_hidden_Kind = &entry_Deleted{v}
}

func (x *Entry) SetAssigned(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Kind = &entry_Assigned{v}
}

func (x *Entry) SetMerged(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Kind = &entry_Merged{v}
}

func (x *Entry) SetCopied(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Kind = &entry_Copied{v}
}

func (x *Entry) SetScattered(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Kind = &entry_Scattered{v}
}

func (x *Entry) SetSwapped(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Kind = &entry_Swapped{v}
}

func (x *Entry) SetEdited(v *Edit) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &entry_Edited{v}
}

func (x *Entry) SetNested(v *Delta) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &entry_Nested{v}
}

func (x *Entry) HasTargets() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Entry) HasNoInsert() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Entry) HasNoUpdate() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Entry) HasKind() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kind != nil
}

func (x *Entry) HasDeleted() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Deleted)
	return ok
}

func (x *Entry) HasAssigned() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Assigned)
	return ok
}

func (x *Entry) HasMerged() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Merged)
	return ok
}

func (x *Entry) HasCopied() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Copied)
	return ok
}

func (x *Entry) HasScattered() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Scattered)
	return ok
}

func (x *Entry) HasSwapped() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Swapped)
	return ok
}

func (x *Entry) HasEdited() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Edited)
	return ok
}

func (x *Entry) HasNested() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*entry_Nested)
	return ok
}

func (x *Entry) ClearTargets() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Targets = nil
}

func (x *Entry) ClearNoInsert() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NoInsert = false
}

func (x *Entry) ClearNoUpdate() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_NoUpdate = false
}

func (x *Entry) ClearKind() {
	x.xxx_hidden_Kind = nil
}

func (x *Entry) ClearDeleted() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Deleted); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Entry) ClearAssigned() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Assigned); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Entry) ClearMerged() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Merged); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Entry) ClearCopied() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Copied); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Entry) ClearScattered() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Scattered); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Entry) ClearSwapped() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Swapped); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Entry) ClearEdited() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Edited); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Entry) ClearNested() {
	if _, ok := x.xxx_hidden_Kind.(*entry_Nested); ok {
		x.xxx_hidden_Kind = nil
	}
}

const Entry_Kind_not_set_case case_Entry_Kind = 0
const Entry_Deleted_case case_Entry_Kind = 4
const Entry_Assigned_case case_Entry_Kind = 5
const Entry_Merged_case case_Entry_Kind = 6
const Entry_Copied_case case_Entry_Kind = 7
const Entry_Scattered_case case_Entry_Kind = 8
const Entry_Swapped_case case_Entry_Kind = 9
const Entry_Edited_case case_Entry_Kind = 14
const Entry_Nested_case case_Entry_Kind = 15

func (x *Entry) WhichKind() case_Entry_Kind {
	if x == nil {
		return Entry_Kind_not_set_case
	}
	switch x.xxx_hidden_Kind.(type) {
	case *entry_Deleted:
		return Entry_Deleted_case
	case *entry_Assigned:
		return Entry_Assigned_case
	case *entry_Merged:
		return Entry_Merged_case
	case *entry_Copied:
		return Entry_Copied_case
	case *entry_Scattered:
		return Entry_Scattered_case
	case *entry_Swapped:
		return Entry_Swapped_case
	case *entry_Edited:
		return Entry_Edited_case
	case *entry_Nested:
		return Entry_Nested_case
	default:
		return Entry_Kind_not_set_case
	}
}

type Entry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// List of target indices for the ops.
	// String keys are length-prefixed and concatenated together.
	Targets []byte
	// no_insert is ignored when patching on the repeated fields.
	NoInsert *bool
	NoUpdate *bool
	// On repeated fields, the target index is updated by default; set no_update=true to insert instead.
	// On repeated fields with no_update=true, index -1 indicates appending to the end of the list and the first backward index is -2, and so on.

	// Fields of oneof xxx_hidden_Kind:
	// Deleted op does not affected by no_insert or no_update.
	Deleted  *bool
	Assigned []byte
	// Target fields must be message type.
	// Bytes are parsed as the target message type and proto.Merge'd into the target field.
	Merged    []byte
	Copied    []byte
	Scattered []byte
	// Swapped op does not affected by no_insert or no_update.
	Swapped []byte
	Edited  *Edit
	Nested  *Delta
	// -- end of xxx_hidden_Kind
}

func (b0 Entry_builder) Build() *Entry {
	m0 := &Entry{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Targets != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Targets = b.Targets
	}
	if b.NoInsert != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_NoInsert = *b.NoInsert
	}
	if b.NoUpdate != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_NoUpdate = *b.NoUpdate
	}
	if b.Deleted != nil {
		x.xxx_hidden_Kind = &entry_Deleted{*b.Deleted}
	}
	if b.Assigned != nil {
		x.xxx_hidden_Kind = &entry_Assigned{b.Assigned}
	}
	if b.Merged != nil {
		x.xxx_hidden_Kind = &entry_Merged{b.Merged}
	}
	if b.Copied != nil {
		x.xxx_hidden_Kind = &entry_Copied{b.Copied}
	}
	if b.Scattered != nil {
		x.xxx_hidden_Kind = &entry_Scattered{b.Scattered}
	}
	if b.Swapped != nil {
		x.xxx_hidden_Kind = &entry_Swapped{b.Swapped}
	}
	if b.Edited != nil {
		x.xxx_hidden_Kind = &entry_Edited{b.Edited}
	}
	if b.Nested != nil {
		x.xxx_hidden_Kind = &entry_Nested{b.Nested}
	}
	return m0
}

type case_Entry_Kind protoreflect.FieldNumber

func (x case_Entry_Kind) String() string {
	md := file_proto_diff_delta_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isEntry_Kind interface {
	isEntry_Kind()
}

type entry_Deleted struct {
	// Deleted op does not affected by no_insert or no_update.
	Deleted bool `protobuf:"varint,4,opt,name=deleted,oneof"`
}

type entry_Assigned struct {
	Assigned []byte `protobuf:"bytes,5,opt,name=assigned,oneof"`
}

type entry_Merged struct {
	// Target fields must be message type.
	// Bytes are parsed as the target message type and proto.Merge'd into the target field.
	Merged []byte `protobuf:"bytes,6,opt,name=merged,oneof"`
}

type entry_Copied struct {
	Copied []byte `protobuf:"bytes,7,opt,name=copied,oneof"` // Index
}

type entry_Scattered struct {
	Scattered []byte `protobuf:"bytes,8,opt,name=scattered,oneof"` // Index
}

type entry_Swapped struct {
	// Swapped op does not affected by no_insert or no_update.
	Swapped []byte `protobuf:"bytes,9,opt,name=swapped,oneof"` // Index
}

type entry_Edited struct {
	Edited *Edit `protobuf:"bytes,14,opt,name=edited,oneof"`
}

type entry_Nested struct {
	Nested *Delta `protobuf:"bytes,15,opt,name=nested,oneof"`
}

func (*entry_Deleted) isEntry_Kind() {}

func (*entry_Assigned) isEntry_Kind() {}

func (*entry_Merged) isEntry_Kind() {}

func (*entry_Copied) isEntry_Kind() {}

func (*entry_Scattered) isEntry_Kind() {}

func (*entry_Swapped) isEntry_Kind() {}

func (*entry_Edited) isEntry_Kind() {}

func (*entry_Nested) isEntry_Kind() {}

type Edit struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Method isEdit_Method          `protobuf_oneof:"method"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Edit) Reset() {
	*x = Edit{}
	mi := &file_proto_diff_delta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edit) ProtoMessage() {}

func (x *Edit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diff_delta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Edit) GetMyers() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Method.(*edit_Myers); ok {
			return x.Myers
		}
	}
	return nil
}

func (x *Edit) SetMyers(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Method = &edit_Myers{v}
}

func (x *Edit) HasMethod() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Method != nil
}

func (x *Edit) HasMyers() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Method.(*edit_Myers)
	return ok
}

func (x *Edit) ClearMethod() {
	x.xxx_hidden_Method = nil
}

func (x *Edit) ClearMyers() {
	if _, ok := x.xxx_hidden_Method.(*edit_Myers); ok {
		x.xxx_hidden_Method = nil
	}
}

const Edit_Method_not_set_case case_Edit_Method = 0
const Edit_Myers_case case_Edit_Method = 1

func (x *Edit) WhichMethod() case_Edit_Method {
	if x == nil {
		return Edit_Method_not_set_case
	}
	switch x.xxx_hidden_Method.(type) {
	case *edit_Myers:
		return Edit_Myers_case
	default:
		return Edit_Method_not_set_case
	}
}

type Edit_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Method:
	Myers []byte
	// -- end of xxx_hidden_Method
}

func (b0 Edit_builder) Build() *Edit {
	m0 := &Edit{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Myers != nil {
		x.xxx_hidden_Method = &edit_Myers{b.Myers}
	}
	return m0
}

type case_Edit_Method protoreflect.FieldNumber

func (x case_Edit_Method) String() string {
	md := file_proto_diff_delta_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isEdit_Method interface {
	isEdit_Method()
}

type edit_Myers struct {
	Myers []byte `protobuf:"bytes,1,opt,name=myers,oneof"`
}

func (*edit_Myers) isEdit_Method() {}

var File_proto_diff_delta_proto protoreflect.FileDescriptor

const file_proto_diff_delta_proto_rawDesc = "" +
	"\n" +
	"\x16proto/diff/delta.proto\x12\x04diff\".\n" +
	"\x05Delta\x12%\n" +
	"\aentries\x18\x01 \x03(\v2\v.diff.EntryR\aentries\"\xda\x02\n" +
	"\x05Entry\x12\x18\n" +
	"\atargets\x18\x01 \x01(\fR\atargets\x12\x1b\n" +
	"\tno_insert\x18\x02 \x01(\bR\bnoInsert\x12\x1b\n" +
	"\tno_update\x18\x03 \x01(\bR\bnoUpdate\x12\x1a\n" +
	"\adeleted\x18\x04 \x01(\bH\x00R\adeleted\x12\x1c\n" +
	"\bassigned\x18\x05 \x01(\fH\x00R\bassigned\x12\x18\n" +
	"\x06merged\x18\x06 \x01(\fH\x00R\x06merged\x12\x18\n" +
	"\x06copied\x18\a \x01(\fH\x00R\x06copied\x12\x1e\n" +
	"\tscattered\x18\b \x01(\fH\x00R\tscattered\x12\x1a\n" +
	"\aswapped\x18\t \x01(\fH\x00R\aswapped\x12$\n" +
	"\x06edited\x18\x0e \x01(\v2\n" +
	".diff.EditH\x00R\x06edited\x12%\n" +
	"\x06nested\x18\x0f \x01(\v2\v.diff.DeltaH\x00R\x06nestedB\x06\n" +
	"\x04kind\"(\n" +
	"\x04Edit\x12\x16\n" +
	"\x05myers\x18\x01 \x01(\fH\x00R\x05myersB\b\n" +
	"\x06methodB'Z%github.com/lesomnus/protobuf-diff/dpbb\beditionsp\xe8\a"

var file_proto_diff_delta_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_diff_delta_proto_goTypes = []any{
	(*Delta)(nil), // 0: diff.Delta
	(*Entry)(nil), // 1: diff.Entry
	(*Edit)(nil),  // 2: diff.Edit
}
var file_proto_diff_delta_proto_depIdxs = []int32{
	1, // 0: diff.Delta.entries:type_name -> diff.Entry
	2, // 1: diff.Entry.edited:type_name -> diff.Edit
	0, // 2: diff.Entry.nested:type_name -> diff.Delta
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_diff_delta_proto_init() }
func file_proto_diff_delta_proto_init() {
	if File_proto_diff_delta_proto != nil {
		return
	}
	file_proto_diff_delta_proto_msgTypes[1].OneofWrappers = []any{
		(*entry_Deleted)(nil),
		(*entry_Assigned)(nil),
		(*entry_Merged)(nil),
		(*entry_Copied)(nil),
		(*entry_Scattered)(nil),
		(*entry_Swapped)(nil),
		(*entry_Edited)(nil),
		(*entry_Nested)(nil),
	}
	file_proto_diff_delta_proto_msgTypes[2].OneofWrappers = []any{
		(*edit_Myers)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_diff_delta_proto_rawDesc), len(file_proto_diff_delta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_diff_delta_proto_goTypes,
		DependencyIndexes: file_proto_diff_delta_proto_depIdxs,
		MessageInfos:      file_proto_diff_delta_proto_msgTypes,
	}.Build()
	File_proto_diff_delta_proto = out.File
	file_proto_diff_delta_proto_goTypes = nil
	file_proto_diff_delta_proto_depIdxs = nil
}
