// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: diff/segment.proto

package dpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Path struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Segments *[]*FieldSegment       `protobuf:"bytes,1,rep,name=segments"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Path) Reset() {
	*x = Path{}
	mi := &file_diff_segment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_diff_segment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Path) GetSegments() []*FieldSegment {
	if x != nil {
		if x.xxx_hidden_Segments != nil {
			return *x.xxx_hidden_Segments
		}
	}
	return nil
}

func (x *Path) SetSegments(v []*FieldSegment) {
	x.xxx_hidden_Segments = &v
}

type Path_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Segments []*FieldSegment
}

func (b0 Path_builder) Build() *Path {
	m0 := &Path{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Segments = &b.Segments
	return m0
}

type Segment struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Kind isSegment_Kind         `protobuf_oneof:"kind"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_diff_segment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_diff_segment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Segment) GetName() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*segment_Name); ok {
			return x.Name
		}
	}
	return ""
}

func (x *Segment) GetIndex() int64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*segment_Index); ok {
			return x.Index
		}
	}
	return 0
}

func (x *Segment) GetField() *FieldSegment {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*segment_Field); ok {
			return x.Field
		}
	}
	return nil
}

func (x *Segment) GetRange() *RangeSegment {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*segment_Range); ok {
			return x.Range
		}
	}
	return nil
}

func (x *Segment) SetName(v string) {
	x.xxx_hidden_Kind = &segment_Name{v}
}

func (x *Segment) SetIndex(v int64) {
	x.xxx_hidden_Kind = &segment_Index{v}
}

func (x *Segment) SetField(v *FieldSegment) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &segment_Field{v}
}

func (x *Segment) SetRange(v *RangeSegment) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &segment_Range{v}
}

func (x *Segment) HasKind() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kind != nil
}

func (x *Segment) HasName() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*segment_Name)
	return ok
}

func (x *Segment) HasIndex() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*segment_Index)
	return ok
}

func (x *Segment) HasField() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*segment_Field)
	return ok
}

func (x *Segment) HasRange() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*segment_Range)
	return ok
}

func (x *Segment) ClearKind() {
	x.xxx_hidden_Kind = nil
}

func (x *Segment) ClearName() {
	if _, ok := x.xxx_hidden_Kind.(*segment_Name); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Segment) ClearIndex() {
	if _, ok := x.xxx_hidden_Kind.(*segment_Index); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Segment) ClearField() {
	if _, ok := x.xxx_hidden_Kind.(*segment_Field); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Segment) ClearRange() {
	if _, ok := x.xxx_hidden_Kind.(*segment_Range); ok {
		x.xxx_hidden_Kind = nil
	}
}

const Segment_Kind_not_set_case case_Segment_Kind = 0
const Segment_Name_case case_Segment_Kind = 1
const Segment_Index_case case_Segment_Kind = 2
const Segment_Field_case case_Segment_Kind = 13
const Segment_Range_case case_Segment_Kind = 12

func (x *Segment) WhichKind() case_Segment_Kind {
	if x == nil {
		return Segment_Kind_not_set_case
	}
	switch x.xxx_hidden_Kind.(type) {
	case *segment_Name:
		return Segment_Name_case
	case *segment_Index:
		return Segment_Index_case
	case *segment_Field:
		return Segment_Field_case
	case *segment_Range:
		return Segment_Range_case
	default:
		return Segment_Kind_not_set_case
	}
}

type Segment_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Kind:
	// Name of the field or key of the map entry.
	Name *string
	// Field number of the message field or index of the repeated field.
	Index *int64
	// FieldSegment can be used over name or index to select the field more precisely.
	Field *FieldSegment
	Range *RangeSegment
	// -- end of xxx_hidden_Kind
}

func (b0 Segment_builder) Build() *Segment {
	m0 := &Segment{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		x.xxx_hidden_Kind = &segment_Name{*b.Name}
	}
	if b.Index != nil {
		x.xxx_hidden_Kind = &segment_Index{*b.Index}
	}
	if b.Field != nil {
		x.xxx_hidden_Kind = &segment_Field{b.Field}
	}
	if b.Range != nil {
		x.xxx_hidden_Kind = &segment_Range{b.Range}
	}
	return m0
}

type case_Segment_Kind protoreflect.FieldNumber

func (x case_Segment_Kind) String() string {
	md := file_diff_segment_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isSegment_Kind interface {
	isSegment_Kind()
}

type segment_Name struct {
	// Name of the field or key of the map entry.
	Name string `protobuf:"bytes,1,opt,name=name,oneof"`
}

type segment_Index struct {
	// Field number of the message field or index of the repeated field.
	Index int64 `protobuf:"zigzag64,2,opt,name=index,oneof"`
}

type segment_Field struct {
	// FieldSegment can be used over name or index to select the field more precisely.
	Field *FieldSegment `protobuf:"bytes,13,opt,name=field,oneof"`
}

type segment_Range struct {
	Range *RangeSegment `protobuf:"bytes,12,opt,name=range,oneof"`
}

func (*segment_Name) isSegment_Kind() {}

func (*segment_Index) isSegment_Kind() {}

func (*segment_Field) isSegment_Kind() {}

func (*segment_Range) isSegment_Kind() {}

// FieldSegment represents a field segment in the path, which can be identified by either name or number.
// One of name, name_alt, or number must be specified.
// If multiple fields are specified, all of them must match for the segment to be considered a match; otherwise, the operations will fail.
type FieldSegment struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_NameAlt     *string                `protobuf:"bytes,2,opt,name=name_alt,json=nameAlt"`
	xxx_hidden_Number      int64                  `protobuf:"zigzag64,3,opt,name=number"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FieldSegment) Reset() {
	*x = FieldSegment{}
	mi := &file_diff_segment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldSegment) ProtoMessage() {}

func (x *FieldSegment) ProtoReflect() protoreflect.Message {
	mi := &file_diff_segment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FieldSegment) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *FieldSegment) GetNameAlt() string {
	if x != nil {
		if x.xxx_hidden_NameAlt != nil {
			return *x.xxx_hidden_NameAlt
		}
		return ""
	}
	return ""
}

func (x *FieldSegment) GetNumber() int64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *FieldSegment) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *FieldSegment) SetNameAlt(v string) {
	x.xxx_hidden_NameAlt = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *FieldSegment) SetNumber(v int64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *FieldSegment) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *FieldSegment) HasNameAlt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *FieldSegment) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *FieldSegment) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *FieldSegment) ClearNameAlt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NameAlt = nil
}

func (x *FieldSegment) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Number = 0
}

type FieldSegment_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of the field or key of the map entry.
	Name *string
	// Alternative name of the field or key of the map entry.
	// For instance, original proto field name is changed in ProtoJSON format.
	NameAlt *string
	// Field number of the message field.
	Number *int64
}

func (b0 FieldSegment_builder) Build() *FieldSegment {
	m0 := &FieldSegment{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Name = b.Name
	}
	if b.NameAlt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_NameAlt = b.NameAlt
	}
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Number = *b.Number
	}
	return m0
}

// RangeSegment represents a range segment in the path, which can be identified by the start and end indices of the repeated field.
// If the field is empty, the range is open to that side.
//
//	xxxxx [_, _) == [0, _) matches all elements.
//	---xx [-2, _) matches last two elements.
//	xx-xx [-2, 2) matches last two elements and first two elements.
//	xx-xx [-2, -4) matches last two elements and up to the fourth last element.
type RangeSegment struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Begin       int64                  `protobuf:"zigzag64,1,opt,name=begin"`
	xxx_hidden_End         int64                  `protobuf:"zigzag64,2,opt,name=end"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RangeSegment) Reset() {
	*x = RangeSegment{}
	mi := &file_diff_segment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeSegment) ProtoMessage() {}

func (x *RangeSegment) ProtoReflect() protoreflect.Message {
	mi := &file_diff_segment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RangeSegment) GetBegin() int64 {
	if x != nil {
		return x.xxx_hidden_Begin
	}
	return 0
}

func (x *RangeSegment) GetEnd() int64 {
	if x != nil {
		return x.xxx_hidden_End
	}
	return 0
}

func (x *RangeSegment) SetBegin(v int64) {
	x.xxx_hidden_Begin = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *RangeSegment) SetEnd(v int64) {
	x.xxx_hidden_End = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *RangeSegment) HasBegin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RangeSegment) HasEnd() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RangeSegment) ClearBegin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Begin = 0
}

func (x *RangeSegment) ClearEnd() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_End = 0
}

type RangeSegment_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Start index of the range, inclusive.
	Begin *int64
	// End index of the range, exclusive.
	End *int64
}

func (b0 RangeSegment_builder) Build() *RangeSegment {
	m0 := &RangeSegment{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Begin != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Begin = *b.Begin
	}
	if b.End != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_End = *b.End
	}
	return m0
}

var File_diff_segment_proto protoreflect.FileDescriptor

const file_diff_segment_proto_rawDesc = "" +
	"\n" +
	"\x12diff/segment.proto\x12\x04diff\"6\n" +
	"\x04Path\x12.\n" +
	"\bsegments\x18\x01 \x03(\v2\x12.diff.FieldSegmentR\bsegments\"\x97\x01\n" +
	"\aSegment\x12\x14\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x12\x16\n" +
	"\x05index\x18\x02 \x01(\x12H\x00R\x05index\x12*\n" +
	"\x05field\x18\r \x01(\v2\x12.diff.FieldSegmentH\x00R\x05field\x12*\n" +
	"\x05range\x18\f \x01(\v2\x12.diff.RangeSegmentH\x00R\x05rangeB\x06\n" +
	"\x04kind\"U\n" +
	"\fFieldSegment\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bname_alt\x18\x02 \x01(\tR\anameAlt\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x12R\x06number\"6\n" +
	"\fRangeSegment\x12\x14\n" +
	"\x05begin\x18\x01 \x01(\x12R\x05begin\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x12R\x03endB'Z%github.com/lesomnus/protobuf-diff/dpbb\beditionsp\xe8\a"

var file_diff_segment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_diff_segment_proto_goTypes = []any{
	(*Path)(nil),         // 0: diff.Path
	(*Segment)(nil),      // 1: diff.Segment
	(*FieldSegment)(nil), // 2: diff.FieldSegment
	(*RangeSegment)(nil), // 3: diff.RangeSegment
}
var file_diff_segment_proto_depIdxs = []int32{
	2, // 0: diff.Path.segments:type_name -> diff.FieldSegment
	2, // 1: diff.Segment.field:type_name -> diff.FieldSegment
	3, // 2: diff.Segment.range:type_name -> diff.RangeSegment
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_diff_segment_proto_init() }
func file_diff_segment_proto_init() {
	if File_diff_segment_proto != nil {
		return
	}
	file_diff_segment_proto_msgTypes[1].OneofWrappers = []any{
		(*segment_Name)(nil),
		(*segment_Index)(nil),
		(*segment_Field)(nil),
		(*segment_Range)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_diff_segment_proto_rawDesc), len(file_diff_segment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_diff_segment_proto_goTypes,
		DependencyIndexes: file_diff_segment_proto_depIdxs,
		MessageInfos:      file_diff_segment_proto_msgTypes,
	}.Build()
	File_diff_segment_proto = out.File
	file_diff_segment_proto_goTypes = nil
	file_diff_segment_proto_depIdxs = nil
}
