// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: diff/value.proto

package dpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NullValue int32

const (
	// Null value.
	NullValue_NULL_VALUE NullValue = 0
)

// Enum value maps for NullValue.
var (
	NullValue_name = map[int32]string{
		0: "NULL_VALUE",
	}
	NullValue_value = map[string]int32{
		"NULL_VALUE": 0,
	}
)

func (x NullValue) Enum() *NullValue {
	p := new(NullValue)
	*p = x
	return p
}

func (x NullValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NullValue) Descriptor() protoreflect.EnumDescriptor {
	return file_diff_value_proto_enumTypes[0].Descriptor()
}

func (NullValue) Type() protoreflect.EnumType {
	return &file_diff_value_proto_enumTypes[0]
}

func (x NullValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Struct struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Fields *[]*KeyValue           `protobuf:"bytes,1,rep,name=fields"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Struct) Reset() {
	*x = Struct{}
	mi := &file_diff_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Struct) ProtoMessage() {}

func (x *Struct) ProtoReflect() protoreflect.Message {
	mi := &file_diff_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Struct) GetFields() []*KeyValue {
	if x != nil {
		if x.xxx_hidden_Fields != nil {
			return *x.xxx_hidden_Fields
		}
	}
	return nil
}

func (x *Struct) SetFields(v []*KeyValue) {
	x.xxx_hidden_Fields = &v
}

type Struct_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Fields []*KeyValue
}

func (b0 Struct_builder) Build() *Struct {
	m0 := &Struct{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Fields = &b.Fields
	return m0
}

type KeyValue struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key   *FieldSegment          `protobuf:"bytes,1,opt,name=key"`
	xxx_hidden_Value *Value                 `protobuf:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_diff_value_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_diff_value_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *KeyValue) GetKey() *FieldSegment {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return nil
}

func (x *KeyValue) GetValue() *Value {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *KeyValue) SetKey(v *FieldSegment) {
	x.xxx_hidden_Key = v
}

func (x *KeyValue) SetValue(v *Value) {
	x.xxx_hidden_Value = v
}

func (x *KeyValue) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *KeyValue) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *KeyValue) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *KeyValue) ClearValue() {
	x.xxx_hidden_Value = nil
}

type KeyValue_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key   *FieldSegment
	Value *Value
}

func (b0 KeyValue_builder) Build() *KeyValue {
	m0 := &KeyValue{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Value = b.Value
	return m0
}

type Value struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Kind isValue_Kind           `protobuf_oneof:"kind"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_diff_value_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_diff_value_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Value) GetN() NullValue {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_N); ok {
			return x.N
		}
	}
	return NullValue_NULL_VALUE
}

func (x *Value) GetF() float64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_F); ok {
			return x.F
		}
	}
	return 0
}

func (x *Value) GetS() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_S); ok {
			return x.S
		}
	}
	return ""
}

func (x *Value) GetB() bool {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_B); ok {
			return x.B
		}
	}
	return false
}

func (x *Value) GetI() int64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_I); ok {
			return x.I
		}
	}
	return 0
}

func (x *Value) GetU() uint64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_U); ok {
			return x.U
		}
	}
	return 0
}

func (x *Value) GetX() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_X); ok {
			return x.X
		}
	}
	return nil
}

func (x *Value) GetM() *Struct {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_M); ok {
			return x.M
		}
	}
	return nil
}

func (x *Value) GetL() *ListValue {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_L); ok {
			return x.L
		}
	}
	return nil
}

func (x *Value) SetN(v NullValue) {
	x.xxx_hidden_Kind = &value_N{v}
}

func (x *Value) SetF(v float64) {
	x.xxx_hidden_Kind = &value_F{v}
}

func (x *Value) SetS(v string) {
	x.xxx_hidden_Kind = &value_S{v}
}

func (x *Value) SetB(v bool) {
	x.xxx_hidden_Kind = &value_B{v}
}

func (x *Value) SetI(v int64) {
	x.xxx_hidden_Kind = &value_I{v}
}

func (x *Value) SetU(v uint64) {
	x.xxx_hidden_Kind = &value_U{v}
}

func (x *Value) SetX(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Kind = &value_X{v}
}

func (x *Value) SetM(v *Struct) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &value_M{v}
}

func (x *Value) SetL(v *ListValue) {
	if v == nil {
		x.xxx_hidden_Kind = nil
		return
	}
	x.xxx_hidden_Kind = &value_L{v}
}

func (x *Value) HasKind() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kind != nil
}

func (x *Value) HasN() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_N)
	return ok
}

func (x *Value) HasF() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_F)
	return ok
}

func (x *Value) HasS() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_S)
	return ok
}

func (x *Value) HasB() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_B)
	return ok
}

func (x *Value) HasI() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_I)
	return ok
}

func (x *Value) HasU() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_U)
	return ok
}

func (x *Value) HasX() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_X)
	return ok
}

func (x *Value) HasM() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_M)
	return ok
}

func (x *Value) HasL() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_L)
	return ok
}

func (x *Value) ClearKind() {
	x.xxx_hidden_Kind = nil
}

func (x *Value) ClearN() {
	if _, ok := x.xxx_hidden_Kind.(*value_N); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearF() {
	if _, ok := x.xxx_hidden_Kind.(*value_F); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearS() {
	if _, ok := x.xxx_hidden_Kind.(*value_S); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearB() {
	if _, ok := x.xxx_hidden_Kind.(*value_B); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearI() {
	if _, ok := x.xxx_hidden_Kind.(*value_I); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearU() {
	if _, ok := x.xxx_hidden_Kind.(*value_U); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearX() {
	if _, ok := x.xxx_hidden_Kind.(*value_X); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearM() {
	if _, ok := x.xxx_hidden_Kind.(*value_M); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearL() {
	if _, ok := x.xxx_hidden_Kind.(*value_L); ok {
		x.xxx_hidden_Kind = nil
	}
}

const Value_Kind_not_set_case case_Value_Kind = 0
const Value_N_case case_Value_Kind = 1
const Value_F_case case_Value_Kind = 2
const Value_S_case case_Value_Kind = 3
const Value_B_case case_Value_Kind = 4
const Value_I_case case_Value_Kind = 7
const Value_U_case case_Value_Kind = 8
const Value_X_case case_Value_Kind = 9
const Value_M_case case_Value_Kind = 10
const Value_L_case case_Value_Kind = 11

func (x *Value) WhichKind() case_Value_Kind {
	if x == nil {
		return Value_Kind_not_set_case
	}
	switch x.xxx_hidden_Kind.(type) {
	case *value_N:
		return Value_N_case
	case *value_F:
		return Value_F_case
	case *value_S:
		return Value_S_case
	case *value_B:
		return Value_B_case
	case *value_I:
		return Value_I_case
	case *value_U:
		return Value_U_case
	case *value_X:
		return Value_X_case
	case *value_M:
		return Value_M_case
	case *value_L:
		return Value_L_case
	default:
		return Value_Kind_not_set_case
	}
}

type Value_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Kind:
	N *NullValue
	F *float64
	S *string
	B *bool
	I *int64
	U *uint64
	X []byte
	M *Struct
	L *ListValue
	// -- end of xxx_hidden_Kind
}

func (b0 Value_builder) Build() *Value {
	m0 := &Value{}
	b, x := &b0, m0
	_, _ = b, x
	if b.N != nil {
		x.xxx_hidden_Kind = &value_N{*b.N}
	}
	if b.F != nil {
		x.xxx_hidden_Kind = &value_F{*b.F}
	}
	if b.S != nil {
		x.xxx_hidden_Kind = &value_S{*b.S}
	}
	if b.B != nil {
		x.xxx_hidden_Kind = &value_B{*b.B}
	}
	if b.I != nil {
		x.xxx_hidden_Kind = &value_I{*b.I}
	}
	if b.U != nil {
		x.xxx_hidden_Kind = &value_U{*b.U}
	}
	if b.X != nil {
		x.xxx_hidden_Kind = &value_X{b.X}
	}
	if b.M != nil {
		x.xxx_hidden_Kind = &value_M{b.M}
	}
	if b.L != nil {
		x.xxx_hidden_Kind = &value_L{b.L}
	}
	return m0
}

type case_Value_Kind protoreflect.FieldNumber

func (x case_Value_Kind) String() string {
	md := file_diff_value_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isValue_Kind interface {
	isValue_Kind()
}

type value_N struct {
	N NullValue `protobuf:"varint,1,opt,name=n,enum=diff.NullValue,oneof"`
}

type value_F struct {
	F float64 `protobuf:"fixed64,2,opt,name=f,oneof"`
}

type value_S struct {
	S string `protobuf:"bytes,3,opt,name=s,oneof"`
}

type value_B struct {
	B bool `protobuf:"varint,4,opt,name=b,oneof"`
}

type value_I struct {
	I int64 `protobuf:"zigzag64,7,opt,name=i,oneof"`
}

type value_U struct {
	U uint64 `protobuf:"varint,8,opt,name=u,oneof"`
}

type value_X struct {
	X []byte `protobuf:"bytes,9,opt,name=x,oneof"`
}

type value_M struct {
	M *Struct `protobuf:"bytes,10,opt,name=m,oneof"`
}

type value_L struct {
	L *ListValue `protobuf:"bytes,11,opt,name=l,oneof"`
}

func (*value_N) isValue_Kind() {}

func (*value_F) isValue_Kind() {}

func (*value_S) isValue_Kind() {}

func (*value_B) isValue_Kind() {}

func (*value_I) isValue_Kind() {}

func (*value_U) isValue_Kind() {}

func (*value_X) isValue_Kind() {}

func (*value_M) isValue_Kind() {}

func (*value_L) isValue_Kind() {}

type ListValue struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Values *[]*Value              `protobuf:"bytes,1,rep,name=values"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_diff_value_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_diff_value_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListValue) GetValues() []*Value {
	if x != nil {
		if x.xxx_hidden_Values != nil {
			return *x.xxx_hidden_Values
		}
	}
	return nil
}

func (x *ListValue) SetValues(v []*Value) {
	x.xxx_hidden_Values = &v
}

type ListValue_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Values []*Value
}

func (b0 ListValue_builder) Build() *ListValue {
	m0 := &ListValue{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Values = &b.Values
	return m0
}

var File_diff_value_proto protoreflect.FileDescriptor

const file_diff_value_proto_rawDesc = "" +
	"\n" +
	"\x10diff/value.proto\x12\x04diff\x1a\x12diff/segment.proto\"0\n" +
	"\x06Struct\x12&\n" +
	"\x06fields\x18\x01 \x03(\v2\x0e.diff.KeyValueR\x06fields\"S\n" +
	"\bKeyValue\x12$\n" +
	"\x03key\x18\x01 \x01(\v2\x12.diff.FieldSegmentR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.diff.ValueR\x05value\"\xcf\x01\n" +
	"\x05Value\x12\x1f\n" +
	"\x01n\x18\x01 \x01(\x0e2\x0f.diff.NullValueH\x00R\x01n\x12\x0e\n" +
	"\x01f\x18\x02 \x01(\x01H\x00R\x01f\x12\x0e\n" +
	"\x01s\x18\x03 \x01(\tH\x00R\x01s\x12\x0e\n" +
	"\x01b\x18\x04 \x01(\bH\x00R\x01b\x12\x0e\n" +
	"\x01i\x18\a \x01(\x12H\x00R\x01i\x12\x0e\n" +
	"\x01u\x18\b \x01(\x04H\x00R\x01u\x12\x0e\n" +
	"\x01x\x18\t \x01(\fH\x00R\x01x\x12\x1c\n" +
	"\x01m\x18\n" +
	" \x01(\v2\f.diff.StructH\x00R\x01m\x12\x1f\n" +
	"\x01l\x18\v \x01(\v2\x0f.diff.ListValueH\x00R\x01lB\x06\n" +
	"\x04kind\"0\n" +
	"\tListValue\x12#\n" +
	"\x06values\x18\x01 \x03(\v2\v.diff.ValueR\x06values*\x1b\n" +
	"\tNullValue\x12\x0e\n" +
	"\n" +
	"NULL_VALUE\x10\x00B'Z%github.com/lesomnus/protobuf-diff/dpbb\beditionsp\xe8\a"

var file_diff_value_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_diff_value_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_diff_value_proto_goTypes = []any{
	(NullValue)(0),       // 0: diff.NullValue
	(*Struct)(nil),       // 1: diff.Struct
	(*KeyValue)(nil),     // 2: diff.KeyValue
	(*Value)(nil),        // 3: diff.Value
	(*ListValue)(nil),    // 4: diff.ListValue
	(*FieldSegment)(nil), // 5: diff.FieldSegment
}
var file_diff_value_proto_depIdxs = []int32{
	2, // 0: diff.Struct.fields:type_name -> diff.KeyValue
	5, // 1: diff.KeyValue.key:type_name -> diff.FieldSegment
	3, // 2: diff.KeyValue.value:type_name -> diff.Value
	0, // 3: diff.Value.n:type_name -> diff.NullValue
	1, // 4: diff.Value.m:type_name -> diff.Struct
	4, // 5: diff.Value.l:type_name -> diff.ListValue
	3, // 6: diff.ListValue.values:type_name -> diff.Value
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_diff_value_proto_init() }
func file_diff_value_proto_init() {
	if File_diff_value_proto != nil {
		return
	}
	file_diff_segment_proto_init()
	file_diff_value_proto_msgTypes[2].OneofWrappers = []any{
		(*value_N)(nil),
		(*value_F)(nil),
		(*value_S)(nil),
		(*value_B)(nil),
		(*value_I)(nil),
		(*value_U)(nil),
		(*value_X)(nil),
		(*value_M)(nil),
		(*value_L)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_diff_value_proto_rawDesc), len(file_diff_value_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_diff_value_proto_goTypes,
		DependencyIndexes: file_diff_value_proto_depIdxs,
		EnumInfos:         file_diff_value_proto_enumTypes,
		MessageInfos:      file_diff_value_proto_msgTypes,
	}.Build()
	File_diff_value_proto = out.File
	file_diff_value_proto_goTypes = nil
	file_diff_value_proto_depIdxs = nil
}
